###
POST http://localhost:3333/category
Content-Type: application/json
Authorization: Basic "abc:123"

{
    "enterpriseId": "8861d131-7274-466b-851e-414677e203e6",
    "name": "categoryFake",
    "description": "logo.png"
}


###
PUT http://localhost:3333/category
Content-Type: application/json
Authorization: Basic "abc:123"

###
DELETE http://localhost:3333/category
Content-Type: application/json
Authorization: Basic "abc:123"

###
GET http://localhost:3333/category
Content-Type: application/json
Authorization: Basic "abc:123"